import { Project } from '@/types/project';

export const mockProjects: Project[] = [
  {
    id: '1',
    name: 'Boundless Platform',
    description:
      'A decentralized crowdfunding and grant funding platform built on the Stellar blockchain. Enables transparent, milestone-based funding for ambitious projects and public innovation.',
    image: '/banner.png',
    link: '/projects/boundless',
    tags: ['blockchain', 'crowdfunding', 'grants', 'stellar'],
    category: 'web3',
    type: 'crowdfunding',
    amount: 123000,
    status: 'under_review',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-20T14:30:00Z',
  },
  {
    id: '2',
    name: 'DeFi Protocol Hub',
    description:
      'A comprehensive DeFi protocol aggregator that provides users with the best yields across multiple chains. Features automated portfolio rebalancing and risk management.',
    image: '/banner.png',
    link: '/projects/defi-hub',
    tags: ['defi', 'yield', 'aggregator', 'portfolio'],
    category: 'defi',
    type: 'crowdfunding',
    amount: 85000,
    status: 'approved',
    createdAt: '2024-01-10T09:15:00Z',
    updatedAt: '2024-01-18T16:45:00Z',
  },
  {
    id: '3',
    name: 'NFT Marketplace',
    description:
      'A decentralized NFT marketplace with zero gas fees, built on Layer 2 solutions. Supports multiple blockchains and provides tools for creators to monetize their digital art.',
    image: '/banner.png',
    link: '/projects/nft-marketplace',
    tags: ['nft', 'marketplace', 'layer2', 'creators'],
    category: 'nft',
    type: 'crowdfunding',
    amount: 67000,
    status: 'validated',
    createdAt: '2024-01-12T11:30:00Z',
    updatedAt: '2024-01-19T13:20:00Z',
  },
  // {
  //   id: "4",
  //   name: "DAO Governance Tool",
  //   description: "An advanced governance platform for DAOs with voting mechanisms, proposal management, and treasury controls. Enables transparent decision-making for decentralized organizations.",
  //   image: "/banner.png",
  //   link: "/projects/dao-governance",
  //   tags: ["dao", "governance", "voting", "treasury"],
  //   category: "dao",
  //   type: "grant",
  //   amount: 45000,
  //   status: "rejected",
  //   createdAt: "2024-01-08T14:20:00Z",
  //   updatedAt: "2024-01-16T10:10:00Z",
  // },
  // {
  //   id: "5",
  //   name: "Blockchain Infrastructure",
  //   description: "Building scalable blockchain infrastructure with sharding and cross-chain interoperability. Focuses on high throughput and low latency for enterprise applications.",
  //   image: "/banner.png",
  //   link: "/projects/blockchain-infra",
  //   tags: ["infrastructure", "scalability", "sharding", "enterprise"],
  //   category: "infrastructure",
  //   type: "research",
  //   amount: 200000,
  //   status: "failed",
  //   createdAt: "2024-01-05T08:45:00Z",
  //   updatedAt: "2024-01-17T15:30:00Z",
  // },
  // {
  //   id: "6",
  //   name: "Social Impact DAO",
  //   description: "A DAO focused on funding social impact projects in developing countries. Uses blockchain for transparent fund distribution and impact measurement.",
  //   image: "/banner.png",
  //   link: "/projects/social-impact",
  //   tags: ["social", "impact", "developing", "transparency"],
  //   category: "social_impact",
  //   type: "grant",
  //   amount: 150000,
  //   status: "under_review",
  //   createdAt: "2024-01-14T12:00:00Z",
  //   updatedAt: "2024-01-21T09:15:00Z",
  // },
  // {
  //   id: "7",
  //   name: "Educational Platform",
  //   description: "A decentralized education platform offering blockchain and Web3 courses. Features peer-to-peer learning, credential verification, and micro-certifications.",
  //   image: "/banner.png",
  //   link: "/projects/education-platform",
  //   tags: ["education", "web3", "credentials", "learning"],
  //   category: "education",
  //   type: "crowdfunding",
  //   amount: 75000,
  //   status: "approved",
  //   createdAt: "2024-01-11T16:30:00Z",
  //   updatedAt: "2024-01-19T11:45:00Z",
  // },
  // {
  //   id: "8",
  //   name: "Healthcare Blockchain",
  //   description: "A blockchain solution for healthcare data management and patient privacy. Enables secure sharing of medical records while maintaining patient control.",
  //   image: "/banner.png",
  //   link: "/projects/healthcare-blockchain",
  //   tags: ["healthcare", "privacy", "medical", "data"],
  //   category: "healthcare",
  //   type: "research",
  //   amount: 180000,
  //   status: "validated",
  //   createdAt: "2024-01-13T10:15:00Z",
  //   updatedAt: "2024-01-20T14:20:00Z",
  // },
  // {
  //   id: "9",
  //   name: "Environmental Tracking",
  //   description: "A blockchain-based platform for tracking environmental impact and carbon credits. Provides transparency in sustainability initiatives and carbon offset programs.",
  //   image: "/banner.png",
  //   link: "/projects/environmental-tracking",
  //   tags: ["environment", "carbon", "sustainability", "tracking"],
  //   category: "environment",
  //   type: "grant",
  //   amount: 95000,
  //   status: "rejected",
  //   createdAt: "2024-01-16T13:45:00Z",
  //   updatedAt: "2024-01-22T08:30:00Z",
  // },
  // {
  //   id: "10",
  //   name: "Open Source Tools",
  //   description: "A collection of open-source blockchain development tools and libraries. Aims to accelerate Web3 development and reduce barriers to entry for developers.",
  //   image: "/banner.png",
  //   link: "/projects/open-source-tools",
  //   tags: ["open_source", "development", "tools", "libraries"],
  //   category: "technology",
  //   type: "open_source",
  //   amount: 55000,
  //   status: "failed",
  //   createdAt: "2024-01-09T15:20:00Z",
  //   updatedAt: "2024-01-18T12:10:00Z",
  // },
  // {
  //   id: "11",
  //   name: "Cross-Chain Bridge",
  //   description: "A secure and efficient bridge for transferring assets between different blockchains. Features atomic swaps and multi-signature security for safe cross-chain transactions.",
  //   image: "/banner.png",
  //   link: "/projects/cross-chain-bridge",
  //   tags: ["bridge", "cross_chain", "atomic_swaps", "security"],
  //   category: "infrastructure",
  //   type: "crowdfunding",
  //   amount: 120000,
  //   status: "under_review",
  //   createdAt: "2024-01-07T11:00:00Z",
  //   updatedAt: "2024-01-16T17:45:00Z",
  // },
  // {
  //   id: "12",
  //   name: "Creative NFT Studio",
  //   description: "A platform for artists to create, mint, and sell NFTs with advanced features like royalties, collaborative collections, and interactive experiences.",
  //   image: "/banner.png",
  //   link: "/projects/creative-nft-studio",
  //   tags: ["creative", "art", "nft", "royalties"],
  //   category: "creative",
  //   type: "crowdfunding",
  //   amount: 80000,
  //   status: "approved",
  //   createdAt: "2024-01-12T14:30:00Z",
  //   updatedAt: "2024-01-20T10:15:00Z",
  // },
  // {
  //   id: "13",
  //   name: "DeFi Yield Optimizer",
  //   description: "An automated yield optimization platform that finds the best DeFi opportunities across multiple protocols and automatically rebalances portfolios for maximum returns.",
  //   image: "/banner.png",
  //   link: "/projects/defi-yield-optimizer",
  //   tags: ["defi", "yield", "optimization", "automation"],
  //   category: "defi",
  //   type: "grant",
  //   amount: 110000,
  //   status: "validated",
  //   createdAt: "2024-01-15T09:45:00Z",
  //   updatedAt: "2024-01-21T13:30:00Z",
  // },
  // {
  //   id: "14",
  //   name: "Web3 Identity Solution",
  //   description: "A decentralized identity management system that gives users control over their digital identity. Features zero-knowledge proofs and selective disclosure.",
  //   image: "/banner.png",
  //   link: "/projects/web3-identity",
  //   tags: ["identity", "privacy", "zkp", "decentralized"],
  //   category: "web3",
  //   type: "research",
  //   amount: 160000,
  //   status: "rejected",
  //   createdAt: "2024-01-14T16:15:00Z",
  //   updatedAt: "2024-01-22T11:20:00Z",
  // },
  // {
  //   id: "15",
  //   name: "DAO Treasury Management",
  //   description: "A comprehensive treasury management solution for DAOs with multi-signature wallets, investment strategies, and automated fund allocation based on governance decisions.",
  //   image: "/banner.png",
  //   link: "/projects/dao-treasury",
  //   tags: ["dao", "treasury", "multisig", "governance"],
  //   category: "dao",
  //   type: "crowdfunding",
  //   amount: 90000,
  //   status: "failed",
  //   createdAt: "2024-01-11T12:30:00Z",
  //   updatedAt: "2024-01-19T15:45:00Z",
  // },
  // {
  //   id: "16",
  //   name: "Blockchain Gaming Platform",
  //   description: "A gaming platform that integrates blockchain technology for true ownership of in-game assets, play-to-earn mechanics, and cross-game interoperability.",
  //   image: "/banner.png",
  //   link: "/projects/blockchain-gaming",
  //   tags: ["gaming", "play_to_earn", "nft", "interoperability"],
  //   category: "technology",
  //   type: "crowdfunding",
  //   amount: 140000,
  //   status: "under_review",
  //   createdAt: "2024-01-13T13:20:00Z",
  //   updatedAt: "2024-01-20T16:10:00Z",
  // },
  // {
  //   id: "17",
  //   name: "Supply Chain Tracking",
  //   description: "A blockchain-based supply chain tracking solution that provides end-to-end visibility and transparency for products from manufacturer to consumer.",
  //   image: "/banner.png",
  //   link: "/projects/supply-chain",
  //   tags: ["supply_chain", "tracking", "transparency", "logistics"],
  //   category: "technology",
  //   type: "grant",
  //   amount: 175000,
  //   status: "approved",
  //   createdAt: "2024-01-16T10:45:00Z",
  //   updatedAt: "2024-01-22T14:30:00Z",
  // },
  // {
  //   id: "18",
  //   name: "Decentralized Storage",
  //   description: "A decentralized storage solution that distributes data across multiple nodes for redundancy and security. Features encryption and incentivized storage providers.",
  //   image: "/banner.png",
  //   link: "/projects/decentralized-storage",
  //   tags: ["storage", "decentralized", "encryption", "incentives"],
  //   category: "infrastructure",
  //   type: "open_source",
  //   amount: 130000,
  //   status: "validated",
  //   createdAt: "2024-01-08T15:30:00Z",
  //   updatedAt: "2024-01-17T12:15:00Z",
  // },
  // {
  //   id: "19",
  //   name: "Social Media DAO",
  //   description: "A decentralized social media platform where users own their data and content. Features tokenized communities and content monetization through NFTs.",
  //   image: "/banner.png",
  //   link: "/projects/social-media-dao",
  //   tags: ["social_media", "dao", "content", "monetization"],
  //   category: "social_impact",
  //   type: "crowdfunding",
  //   amount: 100000,
  //   status: "rejected",
  //   createdAt: "2024-01-10T14:15:00Z",
  //   updatedAt: "2024-01-18T18:20:00Z",
  // },
  // {
  //   id: "20",
  //   name: "AI + Blockchain Integration",
  //   description: "A platform that combines AI and blockchain for decentralized AI model training and inference. Enables privacy-preserving machine learning on blockchain data.",
  //   image: "/banner.png",
  //   link: "/projects/ai-blockchain",
  //   tags: ["ai", "machine_learning", "privacy", "decentralized"],
  //   category: "technology",
  //   type: "research",
  //   amount: 250000,
  //   status: "failed",
  //   createdAt: "2024-01-15T11:30:00Z",
  //   updatedAt: "2024-01-21T16:45:00Z",
  // },
];

// Mock campaign details for testing
export const mockCampaignDetails = {
  id: 'campaign-123',
  title: 'Boundless',
  tagline: 'Trustless, decentralized crowdfunding platform',
  description:
    'Boundless is a trustless, decentralized application (dApp) that empowers changemakers and builders to raise funds transparently without intermediaries. Campaigns are structured around clearly defined milestones, with funds held in escrow and released only upon approval. Grant creators can launch programs with rule-based logic, and applicants can apply with confidence knowing their work will be fairly evaluated.',
  category: 'Technology',
  fundAmount: 123000,
  raisedAmount: 0,
  tags: ['web3', 'crowdfunding'],
  thumbnail: '/BOUNDLESS.png',
  creator: {
    name: 'Collins Odumeje',
    avatar: 'https://github.com/shadcn.png',
    verified: true,
  },
  engagement: {
    likes: 0,
    comments: 0,
    backers: 325,
    daysLeft: 90,
  },
  photos: [
    '/BOUNDLESS.png',
    '/BOUNDLESS.png',
    '/BOUNDLESS.png',
    '/BOUNDLESS.png',
  ],
  milestones: [
    {
      id: 'milestone-1',
      title: 'Prototype & Smart Contract Setup',
      description:
        'Develop a functional UI prototype for the crowdfunding and grant flow. Simultaneously, implement and test Soroban smart contracts for escrow logic, milestone validation, and secure fund handling.',
      deliveryDate: 'October 10, 2025',
      fundPercentage: 25,
      fundAmount: 30750,
    },
    {
      id: 'milestone-2',
      title: 'Campaign & Grant Builder Integration',
      description:
        'Integrate campaign creation tools and grant builder functionality into the platform with advanced features and user management.',
      deliveryDate: 'November 15, 2025',
      fundPercentage: 35,
      fundAmount: 43050,
    },
    {
      id: 'milestone-3',
      title: 'Platform Launch & Community Building',
      description:
        'Launch the platform to the public and build a strong community of users and contributors with marketing and partnership initiatives.',
      deliveryDate: 'December 20, 2025',
      fundPercentage: 40,
      fundAmount: 49200,
    },
  ],
  status: 'validated',
};
