name: Branch Protection Setup

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to protect'
        required: true
        default: 'main'
        type: choice
        options:
          - main
          - develop
          - staging

jobs:
  setup-branch-protection:
    name: Setup Branch Protection
    runs-on: ubuntu-latest

    steps:
      - name: Setup Branch Protection Rules
        uses: actions/github-script@v7
        with:
          script: |
            const branch = '${{ github.event.inputs.branch }}';

            console.log(`Setting up branch protection for: ${branch}`);

            try {
              await github.rest.repos.updateBranchProtection({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: branch,
                required_status_checks: {
                  strict: true,
                  contexts: [
                    'Code Quality & Linting',
                    'Build & Test',
                    'Security Audit'
                  ]
                },
                enforce_admins: true,
                required_pull_request_reviews: {
                  required_approving_review_count: 2,
                  dismiss_stale_reviews: true,
                  require_code_owner_reviews: true,
                  require_last_push_approval: true
                },
                restrictions: {
                  users: [],
                  teams: []
                },
                allow_force_pushes: false,
                allow_deletions: false,
                block_creations: false,
                required_conversation_resolution: true,
                lock_branch: false,
                allow_fork_syncing: true
              });
              
              console.log(`✅ Branch protection rules set for ${branch}`);
            } catch (error) {
              console.error(`❌ Failed to set branch protection: ${error.message}`);
              core.setFailed(error.message);
            }
